# Generated by Django 5.2 on 2025-05-31 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_quest_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='departament',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.department'),
        ),
    ]
