# Generated by Django 5.2 on 2026-04-29 20:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='projectnName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=main.models.Project),
        ),
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(null=True, related_name='projects', to='main.department'),
        ),
    ]
