# Generated by Django 5.2 on 2026-05-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_quest_projectnname_alter_project_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='projects', to='main.department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=100),
        ),
    ]
