# Generated by Django 5.2 on 2026-05-21 21:10

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='tag',
            field=models.SlugField(default=1, verbose_name=main.models.Tag),
            preserve_default=False,
        ),
    ]
