# Generated by Django 5.2 on 2026-05-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_quest_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='tag',
            field=models.SlugField(),
        ),
    ]
